### ISSUE TITLE
tailoredprofile.yaml missing description field

### ISSUE THREAD

**Issue by jachtermann** [IBM-Cloud/kube-samples#171]
I noticed that "oc apply" will fail when loading the tailoredprofile.yaml and complains about a missing spec.description field:

```
% oc apply -n openshift-compliance -f https://raw.githubusercontent.com/IBM-Cloud/kube-samples/master/roks-compliance-operator/tailoredprofile.yaml
The TailoredProfile "roks-cis-node" is invalid: spec.description: Required value
```

I was doing this on an OpenShift 4.7 cluster. I have not looked at other versions of OpenShift.

I can resolve this by adding the line 
```
    description: "IBM ROKS tailored scan"
```
in line 8 as shown below...

```
# For more information, see https://cloud.ibm.com/docs/openshift?topic=openshift-compliance-operator
apiVersion: compliance.openshift.io/v1alpha1
kind: TailoredProfile
metadata:
  name: roks-cis-node
  namespace: openshift-compliance
spec:
  description: "IBM ROKS tailored scan"
  setValues:
```

Thanks for the great resources!
